global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'task-manager-flask'
    static_configs:
      - targets: ['app-stage:5000']
    # Nota: Para coletar métricas do Flask, a biblioteca prometheus_client precisaria 
    # estar instalada e expor o endpoint /metrics.
